"""
Financial Assistance API

This FastAPI application provides a RESTful API for finding financial assistance grants
based on patient health conditions and income eligibility. The backend implements a 
data pipeline that:

1. Searches for grants using Tavily API (Search module)
2. Analyzes results with Gemini AI for relevance (Analysis module)
3. Verifies grant status and availability (Verification module)
4. Ranks results by quality and eligibility (Prioritization module)
4. Ranks results by quality and eligibility (Prioritizer module)

The application is designed to be called by a React frontend and returns a curated list
of grants matched to the patient's disease and Federal Poverty Level (FPL) percentage calculated according to 
the patient's income, household size, and state of residence.

Environment Requirements:
  - GEMINI_API_KEY: Google Gemini API key variable for grant analysis and elgibility confirmation
  - TAVILY_API_KEY: Tavily API key variable for grant search by web scraping

Author: DuckDuckCode
"""

import os
import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

# Import analysis pipeline modules
from Normalizer import health_disorder_codes, get_fpl_percentage
from Hunter import hunt_for_grants
from analyst import evaluate_grants
from sentinel import check_funding_status
from prioritizer import rank_results

# Load environment variables from .env file without hardcoding keys in source code for security and flexibility
load_dotenv()

# Initialize FastAPI application
app = FastAPI()

# Enable CORS (Cross-Origin Resource Sharing) so the React frontend can call this API
# In production, restrict allow_origins to specific domains instead of "*"
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://aarah-s.github.io",
        "http://localhost:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class HuntRequest(BaseModel):
    """
    Schema for the /api/hunt endpoint request.
    
    Attributes:
        code (str): Two-letter disease code (e.g., "HD" for Heart Disease, "DB" for Diabetes)
        income (float): Annual household income in USD
        hhSize (int): Number of people in the household
        state (str): Two-letter state code (e.g., "TX", "CA", "NY")
    """
    code: str
    income: float
    hhSize: int
    state: str


@app.post("/api/hunt")
async def api_hunt(req: HuntRequest):
    """
    Main endpoint for finding financial assistance grants.
    
    This endpoint orchestrates the complete grant-finding pipeline:
    1. Validates the disease code against known conditions
    2. Calculates Federal Poverty Level (FPL) percentage based on income and household size
    3. Searches for relevant grants using Tavily API
    4. Analyzes results with Gemini AI for quality and relevance
    5. Verifies current grant status (open/closed/exhausted)
    6. Ranks results by eligibility and priority
    
    Args:
        req (HuntRequest): Request containing disease code, income, household size, and state
        
    Returns:
        dict: Contains:
            - disease (str): Full disease name
            - fpl_percentage (float): Calculated FPL percentage (100 = at federalpoverty level)
            - grants (list): Ranked list of matching grants with eligibility details generated by the pipeline
            
    Raises:
        HTTPException: 400 if invalid disease code, 500 if processing error
    """
    try:
        # Step 1: Validate disease code
        if req.code not in health_disorder_codes:
            raise HTTPException(
                status_code=400, 
                detail=f"Invalid disease code '{req.code}'. Use codes like HD, CA, DB, OB, etc."
            )
        
        disease_name = health_disorder_codes[req.code]
        
        # Step 2: Calculate FPL percentage
        # FPL % > 100 means above poverty line, < 100 means below (more eligible for assistance)
        fpl_pct = get_fpl_percentage(req.income, req.hhSize, req.state)
        
        # Step 3: Search for grants with Tavily API
        raw_results = hunt_for_grants(disease_name, fpl_pct)
        
        # Step 4: Analyze and filter grants with Gemini AI
        # Removes irrelevant results and adds eligibility scoring
        analyzed = evaluate_grants(fpl_pct, disease_name, raw_results)
        
        # Step 5: Verify grant status to check if they are still open or have been exhausted
        verified = await check_funding_status(analyzed)
        
        # Step 6: Rank results by priority combining relevance, eligibility, and urgency
        final_ranked = rank_results(verified)
        
        # Return curated results to frontend with disease name, FPL percentage, and ranked grants
        return {
            "disease": disease_name,
            "fpl_percentage": fpl_pct,
            "grants": final_ranked
        }
        
    except HTTPException:
        # Re-raise HTTP exceptions (like invalid disease code)
        raise
    except Exception as e:
        # Catch unexpected errors and log them
        print(f"Server Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    # Start FastAPI server with auto-reload enabled (for development)
    # In production, set reload=False and use a production ASGI server (gunicorn, etc.)
    uvicorn.run("main:app", host="0.0.0.0", port=int(os.environ.get("PORT", 5000)), reload=False)



